server:
  port: 8001
spring:
  application:
    name: msvc-auth
  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:h2:mem:///testdb
    username: sa
    password: password
config:
  text: "Configure LOCAL environment!"
logging:
  level:
    io:
      r2dbc:
        h2: trace
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
