#Default env vars
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-auth
data:
  application.yaml: |
    server:
      port: 8001
    spring:
      application:
        name: msvc-auth
      data:
        r2dbc:
          repositories:
            enabled: true
      r2dbc:
        url: r2dbc:h2:mem:///testdb
        username: sa
        password: password
    config:
      text: "Configure DEFAULT environment "
    logging:
      level:
        io:
          r2dbc:
            h2: trace

---
#Production env vars
apiVersion: v1
kind: ConfigMap
metadata:
  name: msvc-auth-pdn
data:
  application.yaml: |
    server:
      port: 8001
    spring:
      application:
        name: msvc-auth
      data:
        r2dbc:
          repositories:
            enabled: true
      r2dbc:
        url: r2dbc:h2:mem:///testdb
        username: sa
        password: password
    config:
      text: "Configure PDN environment"
    logging:
      level:
        io:
          r2dbc:
            h2: trace

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-auth
  template:
    metadata:
      labels:
        app: msvc-auth
    spec:
      containers:
        - name: auth-container
          image: gporras/auth:latest
          envFrom:
            - configMapRef:
                name: msvc-auth-pdn
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: config
              mountPath: /home/appuser/config
              readOnly: true
            - name: tmp
              mountPath: /tmp
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: SPRING_CONFIG_NAME
              value: application
            - name: SPRING_CONFIG_LOCATION
              value: file:/home/appuser/config/
      volumes:
        - name: config
          configMap:
            name: msvc-auth-pdn
        - name: tmp
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: msvc-auth
spec:
  ports:
    - port: 8001
      protocol: TCP
      targetPort: 8001
  selector:
    app: msvc-auth
  type: LoadBalancer
